env:
  profile: dev

mongo:
  url: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=service
  database: dev

s3-config:
  bucket: one-god-dev
  bucket_url: https://one-god-dev.s3.ap-south-1.amazonaws.com

content-transformer-config:
  inputContentLocalFilePathPrefixWOScheme: /tmp/one-god-local/input #/Users/akhil/Downloads/tmp/one-god-local/input
  outputContentLocalFilePathPrefixWOScheme: /tmp/one-god-local/output #/Users/akhil/Downloads/tmp/one-god-local/output